# Generated by Django 4.2.3 on 2023-08-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name_plural': 'beneficiaries'},
        ),
        migrations.RenameField(
            model_name='lifeinsurance',
            old_name='contract_conclusion_date',
            new_name='contract_date',
        ),
    ]
