# Generated by Django 4.2.3 on 2023-08-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0002_alter_beneficiary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeinsurance',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insuranceapp.beneficiary'),
        ),
        migrations.AlterField(
            model_name='lifeinsurance',
            name='insured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insuranceapp.insured'),
        ),
        migrations.CreateModel(
            name='HomeInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField()),
                ('valid_from_date', models.DateField()),
                ('valid_to_date', models.DateField()),
                ('sum_assured', models.IntegerField()),
                ('street_and_reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insuranceapp.policyholder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
